spring:
  application:
    name: rate_limitter

rateLimitter:
  algoType: LEAKY_BUCKET
  param1: 10
  param2: 1


# Logging
logging:
  level:
    root: INFO
    "com.example.rate_limitter": DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always